parameters:
    logo_directory:         '%kernel.project_dir%/web/uploads/logos'
    company_directory:      '%kernel.project_dir%/web/uploads/companies'
    gameimage_directory:    '%kernel.project_dir%/web/uploads/gameimages'