maciej_study_homepage:
    path:     /
    defaults: { _controller: MaciejStudyBundle:Default:index }
    
companyform:
    path:   admin/company/form
    defaults: { _controller: MaciejStudyBundle:Company:form }
    
companylist:
    path:  admin/company/list
    defaults: { _controller: MaciejStudyBundle:Company:list }
    
companydelete:
    path: admin/company/delete/{wild}
    defaults: {_controller: MaciejStudyBundle:Company:delete}
    
companyedit:
    path: admin/company/edit/{wild}
    defaults: {_controller: MaciejStudyBundle:Company:edit}
    
companydeleteimage:
    path: admin/company/imagedelete/{wild}
    defaults: { _controller: MaciejStudyBundle:Company:deleteimage}
    
gameform:
    path:   admin/game/form
    defaults: { _controller: MaciejStudyBundle:Game:form }
    
gamelist:
    path:  admin/game/list
    defaults: { _controller: MaciejStudyBundle:Game:list }
    
gamedelete:
    path: admin/game/delete/{wild}
    defaults: {_controller: MaciejStudyBundle:Game:delete}
    
gameedit:
    path: admin/game/edit/{wild}
    defaults: {_controller: MaciejStudyBundle:Game:edit}
    
gamedeleteimage:
    path: admin/game/imagedelete/{wild}
    defaults: { _controller: MaciejStudyBundle:Game:deleteimage}
    
gameimageform:
    path: admin/gameimage/form
    defaults: {_controller : MaciejStudyBundle:GameImage:form}
    
gameimagelist:
    path:  admin/gameimage/list/{wild}
    defaults: { _controller: MaciejStudyBundle:GameImage:list }
    
gameimagedelete:
    path: admin/gameimage/delete/{wild}
    defaults: { _controller: MaciejStudyBundle:GameImage:delete}
    
logout:
    path: /logout
