services:
    LogoHandler:
        class: Maciej\MaciejBundle\Service\LogoHandler
        
    FileUploader:
        class:  Maciej\MaciejBundle\Service\FileUploader
        arguments:
            $args:
                logo :      '%logo_directory%'
                company:    '%company_directory%'
                gameimage:      '%gameimage_directory%'
            $showArgs:
                logo :      '%logo_adress%'
                company:    '%company_adress%'
                gameimage:      '%gameimage_adress%' 
    
    FileUploaderAWS:   
        class: Maciej\MaciejBundle\Service\FileUploaderAWS
        arguments:
            $s3Client: "@amazon.s3_client"  
            $showArgs:
                logo :      '%logo_adressAWS%'
                company:    '%company_adressAWS%'
                gameimage:      '%gameimage_adressAWS%' 
                
    amazon.s3_client:
        class: Aws\S3\S3Client
        arguments:
            -
                version: '2006-03-01'
                region: 'us-east-1'
                credentials:
                    key: %aws_s3_key%
                    secret: %aws_s3_secret%
    
    FileHandlingListener:
        class: Maciej\MaciejBundle\EventListener\FileHandlingListener
        arguments: ['@FileUploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist}
            - { name: doctrine.event_listener, event: preUpdate}
            - { name: doctrine.event_listener, event: preRemove}