maciej_user:
    resource: "@MaciejUserBundle/Resources/config/routing.yml"
    prefix:   /

maciej_study:
    resource: "@MaciejStudyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
