maciej_api2:
    resource: "@MaciejApi2Bundle/Resources/config/routing.yml"
    prefix:   /api2

maciej_api:
    resource: "@MaciejApiBundle/Resources/config/routing.yml"
    prefix:   /api

maciej_user:
    resource: "@MaciejUserBundle/Resources/config/routing.yml"
    prefix:   /

maciej_study:
    resource: "@MaciejStudyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
