
   
usergamelist:
    path: /game/list/{page}
    defaults: { _controller: MaciejUserBundle:Game:list, page: 1 }
    
usergamesearch:
    path: /game/search
    defaults: { _controller: MaciejUserBundle:Game:search, page: 1 }
  
usergamesingle:
    path: /game/game/{name}
    defaults: { _controller: MaciejUserBundle:Game:single }
      
usercompanylist:
    path: /company/list
    defaults: { _controller: MaciejUserBundle:Company:list }
    
usercompanysingle:
    path: /company/{name}
    defaults: { _controller: MaciejUserBundle:Company:single }
    
login:
    path: /login
    defaults: { _controller: MaciejUserBundle:Security:login}
    

   
    
