
   
usergamelist:
    path: /game/list/{pagee}
    defaults: { _controller: MaciejUserBundle:Game:list, pagee: 1 }
  
usergamesingle:
    path: /game/single/{id}
    defaults: { _controller: MaciejUserBundle:Game:single }

      
usercompanylist:
    path: /company/list
    defaults: { _controller: MaciejUserBundle:Company:list }
    
usercompanysingle:
    path: /company/single/{id}
    defaults: { _controller: MaciejUserBundle:Company:single }

    
login:
    path: /login
    defaults: { _controller: MaciejUserBundle:Security:login}
    
userregister:
    path: /register
    defaults: { _controller: MaciejUserBundle:Security:register}
    
notfound:
    path: /notfound
    defaults: { _controller: MaciejUserBundle:Company:NotFound }
    
usercompanysearch:
  path: /company/search
  defaults: { _controller: MaciejUserBundle:Company:companySearch}
  
usergamesearch:
  path: /game/search
  defaults: { _controller: MaciejUserBundle:Game:gameSearch}

    

   
    
