maciej_api2_homepage:
    path:     /
    defaults: { _controller: MaciejApi2Bundle:Default:index }
    
api2companylist:
    path:   /company/list
    defaults: { _controller: MaciejApi2Bundle:Company:getlist }
    methods: GET
    
api2companysingle:
    path:   /company/single/{id}
    defaults: { _controller: MaciejApi2Bundle:Company:getCompany }
    methods: GET

api2ajaxlistupdatecompany:
    path:  /company/ajax/update
    defaults: { _controller: MaciejApi2Bundle:Company:getListByCriteria}

api2gamelist:
    path:   /game/list
    defaults: { _controller: MaciejApi2Bundle:Game:getlist }
    methods: GET
    
api2gamesingle:
    path:   /game/single/{id}
    defaults: { _controller: MaciejApi2Bundle:Game:GetGame }
    methods: GET
    
api2ajaxlistupdategame:
    path:  /game/ajax/update
    defaults: { _controller: MaciejApi2Bundle:Game:getListByCriteria}
    
api2ajaxgameimageshow:
    path:   /gameimage/ajax/show
    defaults: { _controller: MaciejApi2Bundle:GameImage:getImagesByTitle}